name: publish

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      # https://github.com/aws-actions/amazon-ecr-login
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::876460094794:role/github-ecr-public-publishing-role
          aws-region: us-east-1
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - run: rustup update stable && rustup default stable
      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: n0i9l8j9
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          pip3 install cargo-lambda
          ./build.sh

          if [[ -z "$TAG_NAME" ]]; then
            TAG_POSTFIX=""
          else
            TAG_POSTFIX=":$TAG_NAME"
          fi
          PACKAGES="dynamodb-export"

          for package in $PACKAGES; do
              echo "Pushing $package"
              docker tag "low_code_lambda/${package}" public.ecr.aws/${REGISTRY_ALIAS}/low_code_lambda/${package}${TAG_POSTFIX}
              docker push public.ecr.aws/${REGISTRY_ALIAS}/low_code_lambda/${package}${TAG_POSTFIX}
          done
