name: pull_request

on:
  pull_request: {}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - uses: google/osv-scanner/actions/scanner@main
      - run: |
          pip3 install cargo-lambda
          ./build.sh
      - run: cargo test --verbose
