name: pull_request

on:
  pull_request: {}

jobs:
  osv-scanner:
    permissions:
      actions: read
      security-events: write
      contents: read
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.2.2"

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup update stable && rustup default stable
      - run: |
          pip3 install cargo-lambda
          cargo lambda build
      - run: cargo test --verbose
